spring:
  application:
    name: datart-server

  datasource:
    druid:
      mysql:
        usePingMethod: false

  main:
    banner-mode: off

  profiles:
    include: config
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  web:
    resources:
      static-locations: file:${datart.env.file-path}

  messages:
    basename: i18n.datart_i18n

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: false

  quartz:
    job-store-type: jdbc
    scheduler-name: DatartScheduleCluster
    properties:
      org:
        quartz:
          scheduler:
            instancName: DatartScheduleCluster
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            clusterCheckinInterval: 5000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5

mybatis:
  type-aliases-package: datart.core.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    datart:
      core:
        mappers: info
      data.provider.jdbc: info
  config: config/logback.xml

shiro:
  web:
    enabled: false


datart:
  version: 1.0.0-alpha.2
  server:
    path-prefix: /api/v1