spring:
  application:
    name: datart-server

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: BASE_LINE
    baseline-version: "2022.02.18"
    clean-disabled: true
    clean-on-validation-error: false
    validate-on-migrate: false

  main:
    banner-mode: off

  profiles:
    active: demo,config

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  web:
    resources:
      static-locations: file:${datart.env.file-path}

  messages:
    basename: i18n.datart_i18n

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: false

  quartz:
    job-store-type: jdbc
    scheduler-name: DatartScheduleCluster
    properties:
      org:
        quartz:
          scheduler:
            instancName: DatartScheduleCluster
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            clusterCheckinInterval: 5000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5

mybatis:
  type-aliases-package: datart.core.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    datart:
      core:
        mappers: info
      data.provider.jdbc: info
  config: config/logback.xml

shiro:
  web:
    enabled: false

datart:
  server:
    path-prefix: /api/v1


server:
  port: 8080
  address: 0.0.0.0

  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
